const font = {
  heading: "'Playfair Display', serif",
  body: "'DM Sans', sans-serif",
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const stylesPracticing: Record<string, any> = {
  typography: {
    grammarTopic: {
      fontWeight: 600,
      fontFamily: font.body,
      fontSize: "0.8rem",
      color: "#5b21b6",
      backgroundColor: "#ede9fe",
      borderRadius: "0.5rem",
      padding: "0.35rem 0.75rem",
      display: "inline-block",
      letterSpacing: "0.03em",
    },
    titleGrammar: {
      color: "#1a0a33",
      fontSize: { xs: "1.3rem", sm: "1.5rem", md: "1.6rem" },
      fontWeight: 700,
      fontFamily: font.heading,
      letterSpacing: "-0.01em",
      lineHeight: 1.3,
    },
  },
  paper: {
    mainContent: {
      backgroundColor: "#ffffff",
      borderRadius: "1rem",
      boxShadow: "0 1px 3px rgba(47,15,87,0.06), 0 4px 16px rgba(47,15,87,0.04)",
      border: "1px solid rgba(146,82,224,0.08)",
      padding: { xs: "1.2rem", sm: "1.5rem", md: "2rem" },
      overflow: "hidden",
    },
  },
  box: {
    mainContent: {
      p: { xs: 1.5, sm: 2 },
      width: "100%",
      height: "100%",
      backgroundColor: "#f8f6ff",
    },
  },
  explainingBox: {
    container: {
      backgroundColor: "#ffffff",
      borderRadius: "0.875rem",
      boxShadow: "0 2px 12px rgba(47,15,87,0.04)",
      border: "1px solid #f0ecf8",
      padding: { xs: "1rem", md: "1.4rem" },
      mt: 2,
    },
    title: {
      color: "#5b21b6",
      fontSize: { xs: "0.9rem", md: "1rem" },
      fontWeight: 700,
      fontFamily: font.body,
      mb: 0.8,
      display: "flex",
      alignItems: "center",
      gap: 1,
    },
    text: {
      fontSize: { xs: "0.88rem", md: "0.93rem" },
      color: "#3d3556",
      lineHeight: 1.7,
      fontFamily: font.body,
    },
  },
  formulateBox: {
    container: {
      background: "linear-gradient(135deg, #7a00e9 0%, #5b21b6 100%)",
      borderRadius: "0.875rem",
      padding: { xs: "1rem", md: "1.4rem" },
      mt: 2,
    },
    title: {
      fontWeight: 700,
      color: "#ffffff",
      fontSize: { xs: "0.9rem", md: "1rem" },
      fontFamily: font.body,
      mb: 0.8,
      display: "flex",
      alignItems: "center",
      gap: 1,
    },
    text: {
      fontSize: { xs: "0.88rem", md: "0.93rem" },
      color: "rgba(255,255,255,0.9)",
      lineHeight: 1.7,
      fontFamily: font.body,
      pl: 2,
      borderLeft: "2px solid rgba(255,255,255,0.25)",
      my: 0.5,
    },
  },
  quizSection: {
    container: {
      background: "linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)",
      borderRadius: "1rem",
      border: "1px solid #e4d9f7",
      padding: { xs: "1.2rem", md: "1.5rem" },
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 2,
      textAlign: "center",
    },
    title: {
      color: "#2f0f57",
      fontSize: { xs: "1.1rem", md: "1.25rem" },
      fontWeight: 700,
      fontFamily: font.heading,
      letterSpacing: "0.04em",
    },
    subtitle: {
      color: "#7c6f9b",
      fontSize: "0.85rem",
      fontFamily: font.body,
      maxWidth: 280,
      lineHeight: 1.5,
    },
  },
  quizButton: {
    textTransform: "none",
    fontWeight: 600,
    fontFamily: font.body,
    fontSize: "0.9rem",
    bgcolor: "#7a00e9",
    color: "#fff",
    borderRadius: "0.75rem",
    px: 3,
    py: 1.1,
    boxShadow: "0 4px 14px rgba(122,0,233,0.25)",
    transition: "all 0.3s ease",
    "&:hover": {
      bgcolor: "#6600c7",
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(122,0,233,0.35)",
    },
  },
  progressBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#e8e0f3",
    "& .MuiLinearProgress-bar": {
      borderRadius: 4,
      background: "linear-gradient(90deg, #7a00e9 0%, #9252e0 100%)",
    },
  },
  questionCounter: {
    color: "#7c6f9b",
    fontSize: "0.85rem",
    fontWeight: 600,
    fontFamily: font.body,
  },
  questionBox: {
    backgroundColor: "#f8f6ff",
    borderRadius: "0.875rem",
    border: "1px solid #e4d9f7",
    padding: { xs: "1rem", md: "1.4rem" },
    mb: 2,
  },
  questionText: {
    color: "#1a0a33",
    fontSize: { xs: "0.95rem", md: "1.05rem" },
    fontWeight: 600,
    fontFamily: font.body,
    lineHeight: 1.6,
  },
  optionCard: {
    default: {
      backgroundColor: "#ffffff",
      borderRadius: "0.75rem",
      border: "2px solid #e8e0f3",
      padding: { xs: "0.8rem 1rem", md: "1rem 1.2rem" },
      cursor: "pointer",
      transition: "all 0.2s ease",
      "&:hover": {
        borderColor: "#a78bfa",
        backgroundColor: "#faf5ff",
        transform: "translateY(-1px)",
        boxShadow: "0 2px 8px rgba(122,0,233,0.1)",
      },
    },
    selected: {
      backgroundColor: "#f3edff",
      borderRadius: "0.75rem",
      border: "2px solid #7a00e9",
      padding: { xs: "0.8rem 1rem", md: "1rem 1.2rem" },
      cursor: "pointer",
      transition: "all 0.2s ease",
      boxShadow: "0 2px 12px rgba(122,0,233,0.15)",
    },
    correct: {
      backgroundColor: "#ecfdf5",
      borderRadius: "0.75rem",
      border: "2px solid #10b981",
      padding: { xs: "0.8rem 1rem", md: "1rem 1.2rem" },
      cursor: "default",
    },
    incorrect: {
      backgroundColor: "#fef2f2",
      borderRadius: "0.75rem",
      border: "2px solid #ef4444",
      padding: { xs: "0.8rem 1rem", md: "1rem 1.2rem" },
      cursor: "default",
    },
  },
  optionLabel: {
    color: "#5b21b6",
    fontWeight: 700,
    fontFamily: font.body,
    fontSize: "0.9rem",
    minWidth: 28,
  },
  optionText: {
    color: "#3d3556",
    fontSize: { xs: "0.88rem", md: "0.93rem" },
    fontFamily: font.body,
  },
  explanationBox: {
    backgroundColor: "#fffbeb",
    borderRadius: "0.75rem",
    border: "1px solid #fde68a",
    padding: { xs: "0.8rem", md: "1rem" },
    mt: 2,
  },
  explanationText: {
    color: "#92400e",
    fontSize: "0.85rem",
    fontFamily: font.body,
    lineHeight: 1.6,
  },
  resultsScore: {
    container: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 2,
      py: 3,
    },
    circle: {
      width: 120,
      height: 120,
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
    },
    scoreText: {
      color: "#ffffff",
      fontSize: "2rem",
      fontWeight: 800,
      fontFamily: font.heading,
      lineHeight: 1,
    },
    scoreLabel: {
      color: "rgba(255,255,255,0.85)",
      fontSize: "0.75rem",
      fontFamily: font.body,
      fontWeight: 600,
    },
    message: {
      color: "#1a0a33",
      fontSize: { xs: "1.2rem", md: "1.4rem" },
      fontWeight: 700,
      fontFamily: font.heading,
      textAlign: "center",
    },
  },
  resultItem: {
    correct: {
      backgroundColor: "#ecfdf5",
      borderRadius: "0.5rem",
      border: "1px solid #a7f3d0",
      padding: "0.6rem 1rem",
    },
    incorrect: {
      backgroundColor: "#fef2f2",
      borderRadius: "0.5rem",
      border: "1px solid #fecaca",
      padding: "0.6rem 1rem",
    },
    questionText: {
      fontSize: "0.85rem",
      fontFamily: font.body,
      color: "#3d3556",
    },
  },
  addGrammarButton: {
    textTransform: "none",
    fontWeight: 600,
    fontFamily: font.body,
    fontSize: "0.9rem",
    bgcolor: "#ffffff",
    color: "#5b21b6",
    border: "1px solid #d4bffc",
    borderRadius: "0.75rem",
    px: 3,
    py: 1.1,
    transition: "all 0.3s ease",
    "&:hover": {
      bgcolor: "#faf5ff",
      borderColor: "#a78bfa",
      transform: "translateY(-2px)",
    },
  },
};
